#!/bin/bash

mydir=/home/$LOGNAME/Linux/`date +%Y%m%d`
if [ -d ${mydir} ]
then
	:
else
	mkdir /home/$LOGNAME/Linux/`date +%Y%m%d`
fi
if [ -d ${mydir}/code ]
then 
	:
else
	mkdir /home/$LOGNAME/Linux/`date +%Y%m%d`/code
fi
	scp -r $1 test@192.168.2.100:/wangdao/C_C++方向/短期班/Linux/`date +%Y%m%d`/code/* /home/$LOGNAME/Linux/`date +%Y%m%d`/code
